"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class DeltaPose_t(object):
    """
    Published by the DEIO server in response to a TimestampPair_t request.
    
    Pose convention: delta = T_wc(t1) * T_wc(t0).inv()
    where T_wc is the world-to-camera transform stored internally by DEVO.
    This represents the relative change in the world-to-camera transform
    from frame t0 to frame t1.
    
    Quaternion format: [qx, qy, qz, qw] (xyzw, unit quaternion).
    
    Status codes:
    0 = valid pose
    1 = not_initialized (< 8 keyframes seen; identity pose published)
    2 = no_events (no events found in [t0_us, t1_us]; identity pose published)
    3 = pose_error (internal error retrieving pose; identity pose published)
    """

    __slots__ = ["utime", "t0_us", "t1_us", "status", "tx", "ty", "tz", "qx", "qy", "qz", "qw"]

    __typenames__ = ["int64_t", "int64_t", "int64_t", "int8_t", "double", "double", "double", "double", "double", "double", "double"]

    __dimensions__ = [None, None, None, None, None, None, None, None, None, None, None]

    def __init__(self):
        self.utime = 0
        """ LCM Type: int64_t """
        self.t0_us = 0
        """
        echoed from the request
        LCM Type: int64_t
        """

        self.t1_us = 0
        """
        echoed event window start
        LCM Type: int64_t
        """

        self.status = 0
        """
        echoed event window end
        LCM Type: int8_t
        """

        self.tx = 0.0
        """
        0=valid 1=not_initialized 2=no_events 3=pose_error
        LCM Type: double
        """

        self.ty = 0.0
        """ LCM Type: double """
        self.tz = 0.0
        """ LCM Type: double """
        self.qx = 0.0
        """ LCM Type: double """
        self.qy = 0.0
        """ LCM Type: double """
        self.qz = 0.0
        """ LCM Type: double """
        self.qw = 0.0
        """ LCM Type: double """

    def encode(self):
        buf = BytesIO()
        buf.write(DeltaPose_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qqqbddddddd", self.utime, self.t0_us, self.t1_us, self.status, self.tx, self.ty, self.tz, self.qx, self.qy, self.qz, self.qw))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != DeltaPose_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return DeltaPose_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = DeltaPose_t()
        self.utime, self.t0_us, self.t1_us, self.status, self.tx, self.ty, self.tz, self.qx, self.qy, self.qz, self.qw = struct.unpack(">qqqbddddddd", buf.read(81))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if DeltaPose_t in parents: return 0
        tmphash = (0xc6e00998b936c599) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if DeltaPose_t._packed_fingerprint is None:
            DeltaPose_t._packed_fingerprint = struct.pack(">Q", DeltaPose_t._get_hash_recursive([]))
        return DeltaPose_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", DeltaPose_t._get_packed_fingerprint())[0]

