"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class TimestampPair_t(object):
    """
    Sent by the external algorithm to request delta pose estimation.
    t0_us and t1_us define the event window to process (~100ms gap expected).
    """

    __slots__ = ["utime", "t0_us", "t1_us"]

    __typenames__ = ["int64_t", "int64_t", "int64_t"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.utime = 0
        """ LCM Type: int64_t """
        self.t0_us = 0
        """
        wall-clock time of this request (us), echoed back for pairing
        LCM Type: int64_t
        """

        self.t1_us = 0
        """
        event window start timestamp (microseconds)
        LCM Type: int64_t
        """


    def encode(self):
        buf = BytesIO()
        buf.write(TimestampPair_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qqq", self.utime, self.t0_us, self.t1_us))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != TimestampPair_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return TimestampPair_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = TimestampPair_t()
        self.utime, self.t0_us, self.t1_us = struct.unpack(">qqq", buf.read(24))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if TimestampPair_t in parents: return 0
        tmphash = (0xef7a4e2d5e90e657) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if TimestampPair_t._packed_fingerprint is None:
            TimestampPair_t._packed_fingerprint = struct.pack(">Q", TimestampPair_t._get_hash_recursive([]))
        return TimestampPair_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", TimestampPair_t._get_packed_fingerprint())[0]

