expname = tracker_base

# dataset
datapath = /media/s/rell/tartan

# options
evs = True
eval = True
eval_seqs = 10
ddp = False
amp = True
num_workers = 8

# checkpoints
resume =
fgraph_pickle = fgraph/TartanAirEVS.pickle
train_split = script/splits/tartan/tartan_default_train.txt
val_split = script/splits/tartan/tartan_default_val.txt

# preprocessing / augmentation
patches_per_image = 80
patch_selector = "scorer"
norm = "std2"
randaug = True

# training options
batch = 1
iters = 18 # full 18
steps = 240000 # full 240000
save_freq = 10000 # full 10000
lr = 0.00008
clip = 10.0
n_frames = 15
scale = 1.0

# loss
flow_weight = 1.0
scores_weight = 0.05
gamma = 0.8

# network
dim_inet = 384
dim_fnet = 128
dim = 32
